#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 1
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_CARET = 1,
  sym_end_assertion = 2,
  sym_zero_or_more = 3,
  sym_one_or_more = 4,
  sym_lazy = 5,
  sym_optional = 6,
  aux_sym_literal_character_token1 = 7,
  anon_sym_DOT = 8,
  anon_sym_PERCENT = 9,
  aux_sym_character_class_token1 = 10,
  anon_sym_DASH = 11,
  aux_sym_escaped_character_token1 = 12,
  aux_sym_escape_sequence_token1 = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  sym_pattern = 18,
  sym_start_assertion = 19,
  sym_literal_character = 20,
  sym_any_character = 21,
  sym_character_class = 22,
  sym_character_range = 23,
  sym_escaped_character = 24,
  sym_escape_sequence = 25,
  sym_set_sequence = 26,
  sym_set_class = 27,
  sym_set_character = 28,
  sym_set_escaped = 29,
  sym_set_any = 30,
  sym_character_set_content = 31,
  sym_character_set = 32,
  sym_capture_group = 33,
  aux_sym_pattern_repeat1 = 34,
  aux_sym_character_set_content_repeat1 = 35,
  aux_sym_capture_group_repeat1 = 36,
  alias_sym_ERROR = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CARET] = "^",
  [sym_end_assertion] = "end_assertion",
  [sym_zero_or_more] = "zero_or_more",
  [sym_one_or_more] = "one_or_more",
  [sym_lazy] = "lazy",
  [sym_optional] = "optional",
  [aux_sym_literal_character_token1] = "literal_character_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_PERCENT] = "%",
  [aux_sym_character_class_token1] = "character_class_token1",
  [anon_sym_DASH] = "-",
  [aux_sym_escaped_character_token1] = "escaped_character_token1",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_pattern] = "pattern",
  [sym_start_assertion] = "start_assertion",
  [sym_literal_character] = "literal_character",
  [sym_any_character] = "any_character",
  [sym_character_class] = "character_class",
  [sym_character_range] = "character_range",
  [sym_escaped_character] = "escaped_character",
  [sym_escape_sequence] = "escape_sequence",
  [sym_set_sequence] = "escape_sequence",
  [sym_set_class] = "character_class",
  [sym_set_character] = "literal_character",
  [sym_set_escaped] = "escaped_character",
  [sym_set_any] = "any_character",
  [sym_character_set_content] = "character_set_content",
  [sym_character_set] = "character_set",
  [sym_capture_group] = "capture_group",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_character_set_content_repeat1] = "character_set_content_repeat1",
  [aux_sym_capture_group_repeat1] = "capture_group_repeat1",
  [alias_sym_ERROR] = "ERROR",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CARET] = anon_sym_CARET,
  [sym_end_assertion] = sym_end_assertion,
  [sym_zero_or_more] = sym_zero_or_more,
  [sym_one_or_more] = sym_one_or_more,
  [sym_lazy] = sym_lazy,
  [sym_optional] = sym_optional,
  [aux_sym_literal_character_token1] = aux_sym_literal_character_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_character_class_token1] = aux_sym_character_class_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_escaped_character_token1] = aux_sym_escaped_character_token1,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_pattern] = sym_pattern,
  [sym_start_assertion] = sym_start_assertion,
  [sym_literal_character] = sym_literal_character,
  [sym_any_character] = sym_any_character,
  [sym_character_class] = sym_character_class,
  [sym_character_range] = sym_character_range,
  [sym_escaped_character] = sym_escaped_character,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_set_sequence] = sym_escape_sequence,
  [sym_set_class] = sym_character_class,
  [sym_set_character] = sym_literal_character,
  [sym_set_escaped] = sym_escaped_character,
  [sym_set_any] = sym_any_character,
  [sym_character_set_content] = sym_character_set_content,
  [sym_character_set] = sym_character_set,
  [sym_capture_group] = sym_capture_group,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_character_set_content_repeat1] = aux_sym_character_set_content_repeat1,
  [aux_sym_capture_group_repeat1] = aux_sym_capture_group_repeat1,
  [alias_sym_ERROR] = alias_sym_ERROR,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [sym_end_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_zero_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym_one_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym_lazy] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_literal_character_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_character_class_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escaped_character_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_start_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_character] = {
    .visible = true,
    .named = true,
  },
  [sym_any_character] = {
    .visible = true,
    .named = true,
  },
  [sym_character_class] = {
    .visible = true,
    .named = true,
  },
  [sym_character_range] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_character] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_set_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_set_class] = {
    .visible = true,
    .named = true,
  },
  [sym_set_character] = {
    .visible = true,
    .named = true,
  },
  [sym_set_escaped] = {
    .visible = true,
    .named = true,
  },
  [sym_set_any] = {
    .visible = true,
    .named = true,
  },
  [sym_character_set_content] = {
    .visible = true,
    .named = true,
  },
  [sym_character_set] = {
    .visible = true,
    .named = true,
  },
  [sym_capture_group] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_character_set_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_capture_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_ERROR] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_ERROR,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static TSCharacterRange aux_sym_character_class_token1_character_set_1[] = {
  {'A', 'A'}, {'C', 'D'}, {'L', 'L'}, {'P', 'P'}, {'S', 'S'}, {'U', 'U'}, {'W', 'X'}, {'Z', 'Z'},
  {'a', 'a'}, {'c', 'd'}, {'l', 'l'}, {'p', 'p'}, {'s', 's'}, {'u', 'u'}, {'w', 'x'}, {'z', 'z'},
};

static TSCharacterRange aux_sym_escaped_character_token1_character_set_1[] = {
  {0, '@'}, {'B', 'B'}, {'E', 'K'}, {'M', 'O'}, {'Q', 'R'}, {'T', 'T'}, {'V', 'V'}, {'Y', 'Y'},
  {'[', '`'}, {'b', 'b'}, {'e', 'k'}, {'m', 'o'}, {'q', 'r'}, {'t', 't'}, {'v', 'v'}, {'y', 'y'},
  {'{', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(5);
      if (lookahead == '$') ADVANCE(9);
      if (lookahead == '%') ADVANCE(19);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '+') ADVANCE(11);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '?') ADVANCE(13);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '^') ADVANCE(8);
      if (set_contains(aux_sym_character_class_token1_character_set_1, 16, lookahead)) ADVANCE(20);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 15,
        '\r', 14,
        '%', 19,
        ')', 28,
        '-', 21,
        '.', 18,
        '[', 25,
        '\\', 17,
        ']', 26,
      );
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '%' &&
          (lookahead < '(' || '+' < lookahead) &&
          lookahead != '?' &&
          (lookahead < '[' || '^' < lookahead)) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '$' &&
          (lookahead < '(' || '+' < lookahead) &&
          lookahead != '-' &&
          lookahead != '.' &&
          lookahead != '?' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '^') ADVANCE(14);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 23,
        '\r', 22,
        'A', 20,
        'C', 20,
        'D', 20,
        'L', 20,
        'P', 20,
        'S', 20,
        'U', 20,
        'W', 20,
        'X', 20,
        'Z', 20,
        'a', 20,
        'c', 20,
        'd', 20,
        'l', 20,
        'p', 20,
        's', 20,
        'u', 20,
        'w', 20,
        'x', 20,
        'z', 20,
      );
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 24,
        '\'', 24,
        '0', 24,
        '\\', 24,
        'b', 24,
        'f', 24,
        'n', 24,
        'r', 24,
        't', 24,
        'v', 24,
      );
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '\n', 15,
        '\r', 14,
        '$', 9,
        '%', 19,
        '(', 27,
        ')', 28,
        '*', 10,
        '+', 11,
        '-', 12,
        '.', 18,
        '?', 13,
        '[', 25,
        '\\', 17,
        ']', 26,
        '^', 8,
      );
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_end_assertion);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_zero_or_more);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_one_or_more);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_lazy);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_optional);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_literal_character_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_literal_character_token1);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(14);
      if (lookahead == '%') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '%' &&
          (lookahead < '(' || '+' < lookahead) &&
          lookahead != '-' &&
          lookahead != '.' &&
          lookahead != '?' &&
          (lookahead < '[' || '^' < lookahead)) ADVANCE(14);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_literal_character_token1);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '$' &&
          (lookahead < '(' || '+' < lookahead) &&
          lookahead != '-' &&
          lookahead != '.' &&
          lookahead != '?' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '^') ADVANCE(14);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_literal_character_token1);
      ADVANCE_MAP(
        '"', 24,
        '\'', 24,
        '0', 24,
        '\\', 24,
        'b', 24,
        'f', 24,
        'n', 24,
        'r', 24,
        't', 24,
        'v', 24,
      );
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_character_class_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_escaped_character_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_escaped_character_token1);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(22);
      if ((!eof && set_contains(aux_sym_escaped_character_token1_character_set_1, 17, lookahead))) ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [sym_end_assertion] = ACTIONS(1),
    [sym_zero_or_more] = ACTIONS(1),
    [sym_one_or_more] = ACTIONS(1),
    [sym_lazy] = ACTIONS(1),
    [sym_optional] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [aux_sym_character_class_token1] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_escape_sequence_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_pattern] = STATE(45),
    [sym_start_assertion] = STATE(2),
    [sym_literal_character] = STATE(3),
    [sym_any_character] = STATE(3),
    [sym_character_class] = STATE(3),
    [sym_escaped_character] = STATE(3),
    [sym_escape_sequence] = STATE(3),
    [sym_character_set] = STATE(3),
    [sym_capture_group] = STATE(3),
    [aux_sym_pattern_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_CARET] = ACTIONS(5),
    [sym_end_assertion] = ACTIONS(7),
    [sym_zero_or_more] = ACTIONS(9),
    [sym_one_or_more] = ACTIONS(9),
    [sym_lazy] = ACTIONS(9),
    [sym_optional] = ACTIONS(9),
    [aux_sym_literal_character_token1] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(15),
    [aux_sym_escape_sequence_token1] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
  },
  [2] = {
    [sym_literal_character] = STATE(4),
    [sym_any_character] = STATE(4),
    [sym_character_class] = STATE(4),
    [sym_escaped_character] = STATE(4),
    [sym_escape_sequence] = STATE(4),
    [sym_character_set] = STATE(4),
    [sym_capture_group] = STATE(4),
    [aux_sym_pattern_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_end_assertion] = ACTIONS(25),
    [sym_zero_or_more] = ACTIONS(9),
    [sym_one_or_more] = ACTIONS(9),
    [sym_lazy] = ACTIONS(9),
    [sym_optional] = ACTIONS(9),
    [aux_sym_literal_character_token1] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(15),
    [aux_sym_escape_sequence_token1] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
  },
  [3] = {
    [sym_literal_character] = STATE(5),
    [sym_any_character] = STATE(5),
    [sym_character_class] = STATE(5),
    [sym_escaped_character] = STATE(5),
    [sym_escape_sequence] = STATE(5),
    [sym_character_set] = STATE(5),
    [sym_capture_group] = STATE(5),
    [aux_sym_pattern_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_end_assertion] = ACTIONS(25),
    [sym_zero_or_more] = ACTIONS(9),
    [sym_one_or_more] = ACTIONS(9),
    [sym_lazy] = ACTIONS(9),
    [sym_optional] = ACTIONS(9),
    [aux_sym_literal_character_token1] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(15),
    [aux_sym_escape_sequence_token1] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
  },
  [4] = {
    [sym_literal_character] = STATE(5),
    [sym_any_character] = STATE(5),
    [sym_character_class] = STATE(5),
    [sym_escaped_character] = STATE(5),
    [sym_escape_sequence] = STATE(5),
    [sym_character_set] = STATE(5),
    [sym_capture_group] = STATE(5),
    [aux_sym_pattern_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_end_assertion] = ACTIONS(29),
    [sym_zero_or_more] = ACTIONS(9),
    [sym_one_or_more] = ACTIONS(9),
    [sym_lazy] = ACTIONS(9),
    [sym_optional] = ACTIONS(9),
    [aux_sym_literal_character_token1] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(15),
    [aux_sym_escape_sequence_token1] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
  },
  [5] = {
    [sym_literal_character] = STATE(5),
    [sym_any_character] = STATE(5),
    [sym_character_class] = STATE(5),
    [sym_escaped_character] = STATE(5),
    [sym_escape_sequence] = STATE(5),
    [sym_character_set] = STATE(5),
    [sym_capture_group] = STATE(5),
    [aux_sym_pattern_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_end_assertion] = ACTIONS(33),
    [sym_zero_or_more] = ACTIONS(35),
    [sym_one_or_more] = ACTIONS(35),
    [sym_lazy] = ACTIONS(35),
    [sym_optional] = ACTIONS(35),
    [aux_sym_literal_character_token1] = ACTIONS(38),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_PERCENT] = ACTIONS(44),
    [aux_sym_escape_sequence_token1] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LPAREN] = ACTIONS(53),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(56), 1,
      anon_sym_CARET,
    ACTIONS(58), 1,
      aux_sym_literal_character_token1,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(62), 1,
      anon_sym_PERCENT,
    ACTIONS(64), 1,
      aux_sym_escape_sequence_token1,
    STATE(35), 1,
      sym_set_character,
    STATE(43), 1,
      sym_character_set_content,
    STATE(24), 6,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [30] = 3,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(68), 8,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [50] = 3,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(74), 8,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [70] = 7,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      aux_sym_literal_character_token1,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(62), 1,
      anon_sym_PERCENT,
    ACTIONS(64), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    STATE(10), 7,
      sym_set_sequence,
      sym_set_class,
      sym_set_character,
      sym_set_escaped,
      sym_set_any,
      sym_character_set,
      aux_sym_capture_group_repeat1,
  [98] = 7,
    ACTIONS(80), 1,
      aux_sym_literal_character_token1,
    ACTIONS(83), 1,
      anon_sym_DOT,
    ACTIONS(86), 1,
      anon_sym_PERCENT,
    ACTIONS(89), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(92), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(10), 7,
      sym_set_sequence,
      sym_set_class,
      sym_set_character,
      sym_set_escaped,
      sym_set_any,
      sym_character_set,
      aux_sym_capture_group_repeat1,
  [126] = 2,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 12,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [144] = 2,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 12,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [162] = 3,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(103), 7,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [181] = 3,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(109), 7,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [200] = 2,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 11,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [217] = 3,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(119), 7,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [236] = 6,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      aux_sym_literal_character_token1,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(62), 1,
      anon_sym_PERCENT,
    ACTIONS(64), 1,
      aux_sym_escape_sequence_token1,
    STATE(9), 7,
      sym_set_sequence,
      sym_set_class,
      sym_set_character,
      sym_set_escaped,
      sym_set_any,
      sym_character_set,
      aux_sym_capture_group_repeat1,
  [261] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 11,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [278] = 2,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 11,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [295] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 11,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [312] = 3,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(137), 7,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [331] = 3,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(145), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(143), 7,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [350] = 2,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 11,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [367] = 7,
    ACTIONS(58), 1,
      aux_sym_literal_character_token1,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(62), 1,
      anon_sym_PERCENT,
    ACTIONS(64), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(151), 1,
      anon_sym_RBRACK,
    STATE(35), 1,
      sym_set_character,
    STATE(26), 6,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [394] = 2,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 11,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [411] = 7,
    ACTIONS(157), 1,
      aux_sym_literal_character_token1,
    ACTIONS(160), 1,
      anon_sym_DOT,
    ACTIONS(163), 1,
      anon_sym_PERCENT,
    ACTIONS(166), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(169), 1,
      anon_sym_RBRACK,
    STATE(35), 1,
      sym_set_character,
    STATE(26), 6,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [438] = 2,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 11,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [455] = 2,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    ACTIONS(177), 11,
      sym_end_assertion,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [472] = 7,
    ACTIONS(58), 1,
      aux_sym_literal_character_token1,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(62), 1,
      anon_sym_PERCENT,
    ACTIONS(64), 1,
      aux_sym_escape_sequence_token1,
    STATE(35), 1,
      sym_set_character,
    STATE(40), 1,
      sym_character_set_content,
    STATE(24), 6,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [499] = 1,
    ACTIONS(179), 8,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_DASH,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [510] = 1,
    ACTIONS(181), 7,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [520] = 1,
    ACTIONS(183), 7,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [530] = 1,
    ACTIONS(185), 7,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [540] = 1,
    ACTIONS(187), 7,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [550] = 2,
    ACTIONS(191), 1,
      anon_sym_DASH,
    ACTIONS(189), 5,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_RBRACK,
  [561] = 1,
    ACTIONS(193), 5,
      aux_sym_literal_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_RBRACK,
  [569] = 2,
    ACTIONS(195), 1,
      aux_sym_literal_character_token1,
    STATE(36), 1,
      sym_set_character,
  [576] = 2,
    ACTIONS(197), 1,
      aux_sym_character_class_token1,
    ACTIONS(199), 1,
      aux_sym_escaped_character_token1,
  [583] = 2,
    ACTIONS(201), 1,
      aux_sym_character_class_token1,
    ACTIONS(203), 1,
      aux_sym_escaped_character_token1,
  [590] = 1,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
  [594] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [598] = 1,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
  [602] = 1,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
  [606] = 1,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
  [610] = 1,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 30,
  [SMALL_STATE(8)] = 50,
  [SMALL_STATE(9)] = 70,
  [SMALL_STATE(10)] = 98,
  [SMALL_STATE(11)] = 126,
  [SMALL_STATE(12)] = 144,
  [SMALL_STATE(13)] = 162,
  [SMALL_STATE(14)] = 181,
  [SMALL_STATE(15)] = 200,
  [SMALL_STATE(16)] = 217,
  [SMALL_STATE(17)] = 236,
  [SMALL_STATE(18)] = 261,
  [SMALL_STATE(19)] = 278,
  [SMALL_STATE(20)] = 295,
  [SMALL_STATE(21)] = 312,
  [SMALL_STATE(22)] = 331,
  [SMALL_STATE(23)] = 350,
  [SMALL_STATE(24)] = 367,
  [SMALL_STATE(25)] = 394,
  [SMALL_STATE(26)] = 411,
  [SMALL_STATE(27)] = 438,
  [SMALL_STATE(28)] = 455,
  [SMALL_STATE(29)] = 472,
  [SMALL_STATE(30)] = 499,
  [SMALL_STATE(31)] = 510,
  [SMALL_STATE(32)] = 520,
  [SMALL_STATE(33)] = 530,
  [SMALL_STATE(34)] = 540,
  [SMALL_STATE(35)] = 550,
  [SMALL_STATE(36)] = 561,
  [SMALL_STATE(37)] = 569,
  [SMALL_STATE(38)] = 576,
  [SMALL_STATE(39)] = 583,
  [SMALL_STATE(40)] = 590,
  [SMALL_STATE(41)] = 594,
  [SMALL_STATE(42)] = 598,
  [SMALL_STATE(43)] = 602,
  [SMALL_STATE(44)] = 606,
  [SMALL_STATE(45)] = 610,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_set, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_set, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_set, 5, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set, 5, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_character, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_character, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_assertion, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_assertion, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_character, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_any_character, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 1, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_character, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_character, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_character, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_any_character, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_character, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_character, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set_content, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_character, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_character, 3, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture_group, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_capture_group, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_character, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_escaped, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_sequence, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_class, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_any, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_range, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [211] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lua_patterns(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
