#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  aux_sym_pattern_token1 = 1,
  aux_sym_pattern_token2 = 2,
  anon_sym_CARET = 3,
  sym_end_assertion = 4,
  sym_zero_or_more = 5,
  sym_one_or_more = 6,
  sym_lazy = 7,
  sym_optional = 8,
  aux_sym_literal_character_token1 = 9,
  aux_sym_character_reference_token1 = 10,
  anon_sym_DOT = 11,
  aux_sym_literal_quantifers_token1 = 12,
  anon_sym_PERCENT = 13,
  aux_sym_character_class_token1 = 14,
  anon_sym_DASH = 15,
  aux_sym_escaped_character_token1 = 16,
  aux_sym_escape_sequence_token1 = 17,
  sym_set_character = 18,
  aux_sym_set_escaped_token1 = 19,
  anon_sym_LBRACK = 20,
  anon_sym_RBRACK = 21,
  anon_sym_LPAREN = 22,
  anon_sym_RPAREN = 23,
  sym_pattern = 24,
  sym_start_assertion = 25,
  sym_literal_character = 26,
  sym_character_reference = 27,
  sym_any_character = 28,
  sym_literal_quantifers = 29,
  sym_character_class = 30,
  sym_character_range = 31,
  sym_escaped_character = 32,
  sym_escape_sequence = 33,
  sym_set_sequence = 34,
  sym_set_class = 35,
  sym_set_escaped = 36,
  sym_set_any = 37,
  sym_character_set_content = 38,
  sym_character_set = 39,
  sym_capture_group = 40,
  aux_sym_pattern_repeat1 = 41,
  aux_sym_character_set_content_repeat1 = 42,
  aux_sym_capture_group_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_pattern_token1] = "pattern_token1",
  [aux_sym_pattern_token2] = "pattern_token2",
  [anon_sym_CARET] = "^",
  [sym_end_assertion] = "end_assertion",
  [sym_zero_or_more] = "zero_or_more",
  [sym_one_or_more] = "one_or_more",
  [sym_lazy] = "lazy",
  [sym_optional] = "optional",
  [aux_sym_literal_character_token1] = "literal_character_token1",
  [aux_sym_character_reference_token1] = "character_reference_token1",
  [anon_sym_DOT] = ".",
  [aux_sym_literal_quantifers_token1] = "literal_quantifers_token1",
  [anon_sym_PERCENT] = "%",
  [aux_sym_character_class_token1] = "character_class_token1",
  [anon_sym_DASH] = "-",
  [aux_sym_escaped_character_token1] = "escaped_character_token1",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [sym_set_character] = "literal_character",
  [aux_sym_set_escaped_token1] = "set_escaped_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_pattern] = "pattern",
  [sym_start_assertion] = "start_assertion",
  [sym_literal_character] = "literal_character",
  [sym_character_reference] = "character_reference",
  [sym_any_character] = "any_character",
  [sym_literal_quantifers] = "literal_character",
  [sym_character_class] = "character_class",
  [sym_character_range] = "character_range",
  [sym_escaped_character] = "escaped_character",
  [sym_escape_sequence] = "escape_sequence",
  [sym_set_sequence] = "escape_sequence",
  [sym_set_class] = "character_class",
  [sym_set_escaped] = "escaped_character",
  [sym_set_any] = "any_character",
  [sym_character_set_content] = "character_set_content",
  [sym_character_set] = "character_set",
  [sym_capture_group] = "capture_group",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_character_set_content_repeat1] = "character_set_content_repeat1",
  [aux_sym_capture_group_repeat1] = "capture_group_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_pattern_token1] = aux_sym_pattern_token1,
  [aux_sym_pattern_token2] = aux_sym_pattern_token2,
  [anon_sym_CARET] = anon_sym_CARET,
  [sym_end_assertion] = sym_end_assertion,
  [sym_zero_or_more] = sym_zero_or_more,
  [sym_one_or_more] = sym_one_or_more,
  [sym_lazy] = sym_lazy,
  [sym_optional] = sym_optional,
  [aux_sym_literal_character_token1] = aux_sym_literal_character_token1,
  [aux_sym_character_reference_token1] = aux_sym_character_reference_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_literal_quantifers_token1] = aux_sym_literal_quantifers_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_character_class_token1] = aux_sym_character_class_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_escaped_character_token1] = aux_sym_escaped_character_token1,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [sym_set_character] = sym_literal_character,
  [aux_sym_set_escaped_token1] = aux_sym_set_escaped_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_pattern] = sym_pattern,
  [sym_start_assertion] = sym_start_assertion,
  [sym_literal_character] = sym_literal_character,
  [sym_character_reference] = sym_character_reference,
  [sym_any_character] = sym_any_character,
  [sym_literal_quantifers] = sym_literal_character,
  [sym_character_class] = sym_character_class,
  [sym_character_range] = sym_character_range,
  [sym_escaped_character] = sym_escaped_character,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_set_sequence] = sym_escape_sequence,
  [sym_set_class] = sym_character_class,
  [sym_set_escaped] = sym_escaped_character,
  [sym_set_any] = sym_any_character,
  [sym_character_set_content] = sym_character_set_content,
  [sym_character_set] = sym_character_set,
  [sym_capture_group] = sym_capture_group,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_character_set_content_repeat1] = aux_sym_character_set_content_repeat1,
  [aux_sym_capture_group_repeat1] = aux_sym_capture_group_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_pattern_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [sym_end_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_zero_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym_one_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym_lazy] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_literal_character_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_character_reference_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_quantifers_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_character_class_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escaped_character_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_set_character] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_set_escaped_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_start_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_character] = {
    .visible = true,
    .named = true,
  },
  [sym_character_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_any_character] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_quantifers] = {
    .visible = true,
    .named = true,
  },
  [sym_character_class] = {
    .visible = true,
    .named = true,
  },
  [sym_character_range] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_character] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_set_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_set_class] = {
    .visible = true,
    .named = true,
  },
  [sym_set_escaped] = {
    .visible = true,
    .named = true,
  },
  [sym_set_any] = {
    .visible = true,
    .named = true,
  },
  [sym_character_set_content] = {
    .visible = true,
    .named = true,
  },
  [sym_character_set] = {
    .visible = true,
    .named = true,
  },
  [sym_capture_group] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_character_set_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_capture_group_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 9,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 19,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 15,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 7,
  [37] = 6,
  [38] = 15,
  [39] = 17,
  [40] = 6,
  [41] = 15,
  [42] = 42,
  [43] = 43,
  [44] = 26,
  [45] = 45,
  [46] = 24,
  [47] = 35,
  [48] = 48,
  [49] = 49,
  [50] = 26,
  [51] = 28,
  [52] = 52,
  [53] = 49,
  [54] = 43,
  [55] = 45,
  [56] = 26,
  [57] = 28,
  [58] = 48,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 64,
  [69] = 65,
  [70] = 70,
};

static TSCharacterRange aux_sym_character_class_token1_character_set_1[] = {
  {'A', 'A'}, {'C', 'D'}, {'L', 'L'}, {'P', 'P'}, {'S', 'S'}, {'U', 'U'}, {'W', 'X'}, {'Z', 'Z'},
  {'a', 'a'}, {'c', 'd'}, {'l', 'l'}, {'p', 'p'}, {'s', 's'}, {'u', 'u'}, {'w', 'x'}, {'z', 'z'},
};

static TSCharacterRange aux_sym_escaped_character_token1_character_set_1[] = {
  {0, '@'}, {'B', 'B'}, {'E', 'K'}, {'M', 'O'}, {'Q', 'R'}, {'T', 'T'}, {'V', 'V'}, {'Y', 'Y'},
  {'[', '`'}, {'b', 'b'}, {'e', 'k'}, {'m', 'o'}, {'q', 'r'}, {'t', 't'}, {'v', 'v'}, {'y', 'y'},
  {'{', 0x10ffff},
};

static TSCharacterRange aux_sym_set_escaped_token1_character_set_1[] = {
  {0, '@'}, {'B', 'B'}, {'E', 'K'}, {'M', 'O'}, {'Q', 'R'}, {'T', 'T'}, {'V', 'V'}, {'Y', 'Y'},
  {'\\', '\\'}, {'^', '`'}, {'b', 'b'}, {'e', 'k'}, {'m', 'o'}, {'q', 'r'}, {'t', 't'}, {'v', 'v'},
  {'y', 'y'}, {'{', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(15);
      if (lookahead == '$') ADVANCE(23);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead == '(') ADVANCE(58);
      if (lookahead == ')') ADVANCE(59);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '+') ADVANCE(25);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '?') ADVANCE(27);
      if (lookahead == '[') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead == ']') ADVANCE(57);
      if (lookahead == '^') ADVANCE(22);
      if (set_contains(aux_sym_character_class_token1_character_set_1, 16, lookahead)) ADVANCE(36);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 42,
        '\r', 41,
        '%', 35,
        '.', 33,
        '\\', 52,
        '^', 22,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0 &&
          (lookahead < '\\' || '^' < lookahead)) ADVANCE(41);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 43,
        '\r', 41,
        '%', 35,
        ')', 59,
        '.', 33,
        '[', 55,
        '\\', 52,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(41);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 44,
        '\r', 41,
        '%', 35,
        '.', 33,
        '\\', 52,
        ']', 57,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 45,
        '\r', 41,
        '%', 35,
        '.', 33,
        '[', 55,
        '\\', 52,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(41);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 46,
        '\r', 41,
        '%', 35,
        '*', 24,
        '+', 25,
        '-', 37,
        '.', 33,
        '?', 27,
        '\\', 52,
        ']', 57,
      );
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '\n', 47,
        '\r', 41,
        '%', 35,
        ')', 59,
        '*', 24,
        '+', 25,
        '-', 26,
        '.', 33,
        '?', 27,
        '[', 55,
        '\\', 52,
      );
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(41);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '\n', 48,
        '\r', 41,
        '%', 35,
        '-', 37,
        '.', 33,
        '\\', 52,
        ']', 57,
        '*', 34,
        '+', 34,
        '?', 34,
      );
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '\n', 39,
        '\r', 38,
        'A', 36,
        'C', 36,
        'D', 36,
        'L', 36,
        'P', 36,
        'S', 36,
        'U', 36,
        'W', 36,
        'X', 36,
        'Z', 36,
        'a', 36,
        'c', 36,
        'd', 36,
        'l', 36,
        'p', 36,
        's', 36,
        'u', 36,
        'w', 36,
        'x', 36,
        'z', 36,
      );
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        '\n', 54,
        '\r', 53,
        'A', 36,
        'C', 36,
        'D', 36,
        'L', 36,
        'P', 36,
        'S', 36,
        'U', 36,
        'W', 36,
        'X', 36,
        'Z', 36,
        'a', 36,
        'c', 36,
        'd', 36,
        'l', 36,
        'p', 36,
        's', 36,
        'u', 36,
        'w', 36,
        'x', 36,
        'z', 36,
      );
      if (lookahead != 0 &&
          lookahead != 'Z' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(53);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        '\n', 50,
        '\r', 41,
        '%', 35,
        '*', 24,
        '+', 25,
        '-', 26,
        '.', 33,
        '?', 27,
        '\\', 52,
        ']', 57,
      );
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        'x', 14,
        '"', 40,
        '\'', 40,
        '0', 40,
        '\\', 40,
        'b', 40,
        'f', 40,
        'n', 40,
        'r', 40,
        't', 40,
        'v', 40,
      );
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 16:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 29,
        '\r', 28,
        '$', 23,
        '%', 35,
        '(', 58,
        '.', 33,
        '[', 56,
        '\\', 31,
        '^', 22,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 30,
        '\r', 28,
        '$', 23,
        '%', 35,
        '(', 58,
        '*', 24,
        '+', 25,
        '-', 26,
        '.', 33,
        '?', 27,
        '[', 56,
        '\\', 31,
      );
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 30,
        '\r', 28,
        '$', 23,
        '%', 35,
        '(', 58,
        '.', 33,
        '[', 56,
        '\\', 31,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_pattern_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_pattern_token2);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_end_assertion);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_zero_or_more);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_one_or_more);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_lazy);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_optional);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_literal_character_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_literal_character_token1);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead == '$') ADVANCE(23);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(31);
      if (lookahead == '^') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '-' &&
          lookahead != '.' &&
          lookahead != '?' &&
          lookahead != '[' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_literal_character_token1);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead == '$') ADVANCE(23);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '-' &&
          lookahead != '.' &&
          lookahead != '?' &&
          lookahead != '[' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_literal_character_token1);
      ADVANCE_MAP(
        'x', 14,
        '"', 40,
        '\'', 40,
        '0', 40,
        '\\', 40,
        'b', 40,
        'f', 40,
        'n', 40,
        'r', 40,
        't', 40,
        'v', 40,
      );
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_character_reference_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_literal_quantifers_token1);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_character_class_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_escaped_character_token1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_escaped_character_token1);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '\r') ADVANCE(38);
      if ((!eof && set_contains(aux_sym_escaped_character_token1_character_set_1, 17, lookahead))) ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_set_character);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        '\n', 42,
        '\r', 41,
        '%', 35,
        '.', 33,
        '\\', 52,
        '^', 22,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0 &&
          (lookahead < '\\' || '^' < lookahead)) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        '\n', 43,
        '\r', 41,
        '%', 35,
        ')', 59,
        '.', 33,
        '[', 55,
        '\\', 52,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(41);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        '\n', 44,
        '\r', 41,
        '%', 35,
        '.', 33,
        '\\', 52,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        '\n', 45,
        '\r', 41,
        '%', 35,
        '.', 33,
        '[', 55,
        '\\', 52,
        '*', 34,
        '+', 34,
        '-', 34,
        '?', 34,
      );
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(41);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        '\n', 46,
        '\r', 41,
        '%', 35,
        '*', 24,
        '+', 25,
        '-', 37,
        '.', 33,
        '?', 27,
        '\\', 52,
      );
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        '\n', 47,
        '\r', 41,
        '%', 35,
        ')', 59,
        '*', 24,
        '+', 25,
        '-', 26,
        '.', 33,
        '?', 27,
        '[', 55,
        '\\', 52,
      );
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(41);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        '\n', 48,
        '\r', 41,
        '%', 35,
        '-', 37,
        '.', 33,
        '\\', 52,
        '*', 34,
        '+', 34,
        '?', 34,
      );
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_set_character);
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        '\n', 50,
        '\r', 41,
        '%', 35,
        '*', 24,
        '+', 25,
        '-', 26,
        '.', 33,
        '?', 27,
        '\\', 52,
      );
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_set_character);
      if (lookahead == 'x') ADVANCE(14);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_set_character);
      ADVANCE_MAP(
        'x', 14,
        '"', 40,
        '\'', 40,
        '0', 40,
        '\\', 40,
        'b', 40,
        'f', 40,
        'n', 40,
        'r', 40,
        't', 40,
        'v', 40,
      );
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_set_escaped_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_set_escaped_token1);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '\r') ADVANCE(53);
      if ((!eof && set_contains(aux_sym_set_escaped_token1_character_set_1, 18, lookahead))) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ']') ADVANCE(20);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ')') ADVANCE(21);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 18},
  [27] = {.lex_state = 18},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 18},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 18},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 18},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 11},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 10},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_pattern_token1] = ACTIONS(1),
    [aux_sym_pattern_token2] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [sym_end_assertion] = ACTIONS(1),
    [sym_zero_or_more] = ACTIONS(1),
    [sym_one_or_more] = ACTIONS(1),
    [sym_lazy] = ACTIONS(1),
    [sym_optional] = ACTIONS(1),
    [aux_sym_character_reference_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_literal_quantifers_token1] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [aux_sym_character_class_token1] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_escape_sequence_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_pattern] = STATE(70),
    [sym_start_assertion] = STATE(2),
    [sym_literal_character] = STATE(3),
    [sym_character_reference] = STATE(3),
    [sym_any_character] = STATE(3),
    [sym_literal_quantifers] = STATE(3),
    [sym_character_class] = STATE(3),
    [sym_escaped_character] = STATE(3),
    [sym_escape_sequence] = STATE(3),
    [sym_character_set] = STATE(3),
    [sym_capture_group] = STATE(3),
    [aux_sym_pattern_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_pattern_token1] = ACTIONS(5),
    [aux_sym_pattern_token2] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(9),
    [aux_sym_literal_character_token1] = ACTIONS(11),
    [aux_sym_character_reference_token1] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [aux_sym_literal_quantifers_token1] = ACTIONS(17),
    [anon_sym_PERCENT] = ACTIONS(19),
    [aux_sym_escape_sequence_token1] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(11), 1,
      aux_sym_literal_character_token1,
    ACTIONS(13), 1,
      aux_sym_character_reference_token1,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(19), 1,
      anon_sym_PERCENT,
    ACTIONS(21), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_end_assertion,
    ACTIONS(29), 2,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
    STATE(4), 10,
      sym_literal_character,
      sym_character_reference,
      sym_any_character,
      sym_literal_quantifers,
      sym_character_class,
      sym_escaped_character,
      sym_escape_sequence,
      sym_character_set,
      sym_capture_group,
      aux_sym_pattern_repeat1,
  [47] = 12,
    ACTIONS(11), 1,
      aux_sym_literal_character_token1,
    ACTIONS(13), 1,
      aux_sym_character_reference_token1,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(19), 1,
      anon_sym_PERCENT,
    ACTIONS(21), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_end_assertion,
    ACTIONS(33), 2,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
    STATE(5), 10,
      sym_literal_character,
      sym_character_reference,
      sym_any_character,
      sym_literal_quantifers,
      sym_character_class,
      sym_escaped_character,
      sym_escape_sequence,
      sym_character_set,
      sym_capture_group,
      aux_sym_pattern_repeat1,
  [94] = 12,
    ACTIONS(11), 1,
      aux_sym_literal_character_token1,
    ACTIONS(13), 1,
      aux_sym_character_reference_token1,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(19), 1,
      anon_sym_PERCENT,
    ACTIONS(21), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym_end_assertion,
    ACTIONS(33), 2,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
    STATE(5), 10,
      sym_literal_character,
      sym_character_reference,
      sym_any_character,
      sym_literal_quantifers,
      sym_character_class,
      sym_escaped_character,
      sym_escape_sequence,
      sym_character_set,
      sym_capture_group,
      aux_sym_pattern_repeat1,
  [141] = 12,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 1,
      sym_end_assertion,
    ACTIONS(46), 1,
      aux_sym_literal_character_token1,
    ACTIONS(49), 1,
      aux_sym_character_reference_token1,
    ACTIONS(52), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(58), 1,
      anon_sym_PERCENT,
    ACTIONS(61), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 2,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
    STATE(5), 10,
      sym_literal_character,
      sym_character_reference,
      sym_any_character,
      sym_literal_quantifers,
      sym_character_class,
      sym_escaped_character,
      sym_escape_sequence,
      sym_character_set,
      sym_capture_group,
      aux_sym_pattern_repeat1,
  [188] = 3,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(72), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [211] = 3,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(78), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [234] = 3,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(84), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [257] = 10,
    ACTIONS(88), 1,
      anon_sym_CARET,
    ACTIONS(90), 1,
      aux_sym_character_reference_token1,
    ACTIONS(92), 1,
      anon_sym_DOT,
    ACTIONS(94), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(96), 1,
      anon_sym_PERCENT,
    ACTIONS(98), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(100), 1,
      sym_set_character,
    STATE(42), 1,
      sym_character_reference,
    STATE(65), 1,
      sym_character_set_content,
    STATE(20), 7,
      sym_literal_quantifers,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [294] = 3,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(104), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [317] = 3,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(110), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [340] = 3,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(116), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [363] = 3,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(122), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [386] = 9,
    ACTIONS(126), 1,
      aux_sym_character_reference_token1,
    ACTIONS(128), 1,
      anon_sym_DOT,
    ACTIONS(130), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(132), 1,
      anon_sym_PERCENT,
    ACTIONS(134), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(136), 1,
      sym_set_character,
    ACTIONS(138), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(16), 8,
      sym_character_reference,
      sym_literal_quantifers,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      sym_character_set,
      aux_sym_capture_group_repeat1,
  [421] = 3,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(144), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [444] = 9,
    ACTIONS(148), 1,
      aux_sym_character_reference_token1,
    ACTIONS(151), 1,
      anon_sym_DOT,
    ACTIONS(154), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(157), 1,
      anon_sym_PERCENT,
    ACTIONS(160), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(163), 1,
      sym_set_character,
    ACTIONS(166), 1,
      anon_sym_LBRACK,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(16), 8,
      sym_character_reference,
      sym_literal_quantifers,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      sym_character_set,
      aux_sym_capture_group_repeat1,
  [479] = 3,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(173), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [502] = 10,
    ACTIONS(90), 1,
      aux_sym_character_reference_token1,
    ACTIONS(92), 1,
      anon_sym_DOT,
    ACTIONS(94), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(96), 1,
      anon_sym_PERCENT,
    ACTIONS(98), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(100), 1,
      sym_set_character,
    ACTIONS(177), 1,
      anon_sym_CARET,
    STATE(42), 1,
      sym_character_reference,
    STATE(69), 1,
      sym_character_set_content,
    STATE(20), 7,
      sym_literal_quantifers,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [539] = 9,
    ACTIONS(90), 1,
      aux_sym_character_reference_token1,
    ACTIONS(92), 1,
      anon_sym_DOT,
    ACTIONS(94), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(96), 1,
      anon_sym_PERCENT,
    ACTIONS(98), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(100), 1,
      sym_set_character,
    STATE(42), 1,
      sym_character_reference,
    STATE(64), 1,
      sym_character_set_content,
    STATE(20), 7,
      sym_literal_quantifers,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [573] = 9,
    ACTIONS(90), 1,
      aux_sym_character_reference_token1,
    ACTIONS(92), 1,
      anon_sym_DOT,
    ACTIONS(94), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(96), 1,
      anon_sym_PERCENT,
    ACTIONS(98), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(100), 1,
      sym_set_character,
    ACTIONS(179), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      sym_character_reference,
    STATE(23), 7,
      sym_literal_quantifers,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [607] = 8,
    ACTIONS(126), 1,
      aux_sym_character_reference_token1,
    ACTIONS(128), 1,
      anon_sym_DOT,
    ACTIONS(130), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(132), 1,
      anon_sym_PERCENT,
    ACTIONS(134), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(138), 1,
      anon_sym_LBRACK,
    ACTIONS(181), 1,
      sym_set_character,
    STATE(14), 8,
      sym_character_reference,
      sym_literal_quantifers,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      sym_character_set,
      aux_sym_capture_group_repeat1,
  [639] = 9,
    ACTIONS(90), 1,
      aux_sym_character_reference_token1,
    ACTIONS(92), 1,
      anon_sym_DOT,
    ACTIONS(94), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(96), 1,
      anon_sym_PERCENT,
    ACTIONS(98), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(100), 1,
      sym_set_character,
    STATE(42), 1,
      sym_character_reference,
    STATE(68), 1,
      sym_character_set_content,
    STATE(20), 7,
      sym_literal_quantifers,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [673] = 9,
    ACTIONS(183), 1,
      aux_sym_character_reference_token1,
    ACTIONS(186), 1,
      anon_sym_DOT,
    ACTIONS(189), 1,
      aux_sym_literal_quantifers_token1,
    ACTIONS(192), 1,
      anon_sym_PERCENT,
    ACTIONS(195), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(198), 1,
      sym_set_character,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      sym_character_reference,
    STATE(23), 7,
      sym_literal_quantifers,
      sym_character_range,
      sym_set_sequence,
      sym_set_class,
      sym_set_escaped,
      sym_set_any,
      aux_sym_character_set_content_repeat1,
  [707] = 2,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [724] = 2,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [741] = 2,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    ACTIONS(209), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [758] = 2,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
    ACTIONS(213), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [775] = 2,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
    ACTIONS(217), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [792] = 2,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    ACTIONS(221), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [809] = 2,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(225), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [826] = 2,
    ACTIONS(227), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(144), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      anon_sym_DASH,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [843] = 2,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
    ACTIONS(231), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [860] = 2,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
    ACTIONS(235), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [877] = 2,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
    ACTIONS(239), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [894] = 2,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
    ACTIONS(243), 11,
      aux_sym_pattern_token1,
      aux_sym_pattern_token2,
      sym_end_assertion,
      aux_sym_literal_character_token1,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [911] = 2,
    ACTIONS(245), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(78), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [928] = 2,
    ACTIONS(247), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(72), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [945] = 2,
    ACTIONS(249), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(144), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [962] = 2,
    ACTIONS(251), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(173), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [979] = 2,
    ACTIONS(253), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(72), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [995] = 2,
    ACTIONS(255), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_lazy,
      sym_optional,
    ACTIONS(144), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1011] = 2,
    ACTIONS(259), 1,
      anon_sym_DASH,
    ACTIONS(257), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1024] = 1,
    ACTIONS(261), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [1035] = 1,
    ACTIONS(209), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      anon_sym_DASH,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1046] = 1,
    ACTIONS(263), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [1057] = 1,
    ACTIONS(173), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [1068] = 1,
    ACTIONS(243), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [1079] = 1,
    ACTIONS(265), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [1090] = 1,
    ACTIONS(267), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [1101] = 1,
    ACTIONS(209), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [1112] = 1,
    ACTIONS(217), 8,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
  [1123] = 1,
    ACTIONS(269), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1133] = 1,
    ACTIONS(267), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1143] = 1,
    ACTIONS(261), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1153] = 1,
    ACTIONS(263), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1163] = 1,
    ACTIONS(209), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1173] = 1,
    ACTIONS(217), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1183] = 1,
    ACTIONS(265), 7,
      aux_sym_character_reference_token1,
      anon_sym_DOT,
      aux_sym_literal_quantifers_token1,
      anon_sym_PERCENT,
      aux_sym_escape_sequence_token1,
      sym_set_character,
      anon_sym_RBRACK,
  [1193] = 3,
    ACTIONS(271), 1,
      aux_sym_character_reference_token1,
    ACTIONS(273), 1,
      sym_set_character,
    STATE(52), 1,
      sym_character_reference,
  [1203] = 2,
    ACTIONS(275), 1,
      aux_sym_character_class_token1,
    ACTIONS(277), 1,
      aux_sym_escaped_character_token1,
  [1210] = 2,
    ACTIONS(279), 1,
      aux_sym_character_class_token1,
    ACTIONS(281), 1,
      aux_sym_set_escaped_token1,
  [1217] = 2,
    ACTIONS(283), 1,
      aux_sym_character_class_token1,
    ACTIONS(285), 1,
      aux_sym_set_escaped_token1,
  [1224] = 1,
    ACTIONS(287), 1,
      ts_builtin_sym_end,
  [1228] = 1,
    ACTIONS(289), 1,
      anon_sym_RBRACK,
  [1232] = 1,
    ACTIONS(291), 1,
      anon_sym_RBRACK,
  [1236] = 1,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
  [1240] = 1,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
  [1244] = 1,
    ACTIONS(293), 1,
      anon_sym_RBRACK,
  [1248] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACK,
  [1252] = 1,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 188,
  [SMALL_STATE(7)] = 211,
  [SMALL_STATE(8)] = 234,
  [SMALL_STATE(9)] = 257,
  [SMALL_STATE(10)] = 294,
  [SMALL_STATE(11)] = 317,
  [SMALL_STATE(12)] = 340,
  [SMALL_STATE(13)] = 363,
  [SMALL_STATE(14)] = 386,
  [SMALL_STATE(15)] = 421,
  [SMALL_STATE(16)] = 444,
  [SMALL_STATE(17)] = 479,
  [SMALL_STATE(18)] = 502,
  [SMALL_STATE(19)] = 539,
  [SMALL_STATE(20)] = 573,
  [SMALL_STATE(21)] = 607,
  [SMALL_STATE(22)] = 639,
  [SMALL_STATE(23)] = 673,
  [SMALL_STATE(24)] = 707,
  [SMALL_STATE(25)] = 724,
  [SMALL_STATE(26)] = 741,
  [SMALL_STATE(27)] = 758,
  [SMALL_STATE(28)] = 775,
  [SMALL_STATE(29)] = 792,
  [SMALL_STATE(30)] = 809,
  [SMALL_STATE(31)] = 826,
  [SMALL_STATE(32)] = 843,
  [SMALL_STATE(33)] = 860,
  [SMALL_STATE(34)] = 877,
  [SMALL_STATE(35)] = 894,
  [SMALL_STATE(36)] = 911,
  [SMALL_STATE(37)] = 928,
  [SMALL_STATE(38)] = 945,
  [SMALL_STATE(39)] = 962,
  [SMALL_STATE(40)] = 979,
  [SMALL_STATE(41)] = 995,
  [SMALL_STATE(42)] = 1011,
  [SMALL_STATE(43)] = 1024,
  [SMALL_STATE(44)] = 1035,
  [SMALL_STATE(45)] = 1046,
  [SMALL_STATE(46)] = 1057,
  [SMALL_STATE(47)] = 1068,
  [SMALL_STATE(48)] = 1079,
  [SMALL_STATE(49)] = 1090,
  [SMALL_STATE(50)] = 1101,
  [SMALL_STATE(51)] = 1112,
  [SMALL_STATE(52)] = 1123,
  [SMALL_STATE(53)] = 1133,
  [SMALL_STATE(54)] = 1143,
  [SMALL_STATE(55)] = 1153,
  [SMALL_STATE(56)] = 1163,
  [SMALL_STATE(57)] = 1173,
  [SMALL_STATE(58)] = 1183,
  [SMALL_STATE(59)] = 1193,
  [SMALL_STATE(60)] = 1203,
  [SMALL_STATE(61)] = 1210,
  [SMALL_STATE(62)] = 1217,
  [SMALL_STATE(63)] = 1224,
  [SMALL_STATE(64)] = 1228,
  [SMALL_STATE(65)] = 1232,
  [SMALL_STATE(66)] = 1236,
  [SMALL_STATE(67)] = 1240,
  [SMALL_STATE(68)] = 1244,
  [SMALL_STATE(69)] = 1248,
  [SMALL_STATE(70)] = 1252,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_quantifers, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_quantifers, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_set, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_character, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_character, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_character, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_character, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_character, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_any_character, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_reference, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_reference, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_capture_group_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_set, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set_content, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [183] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [186] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [192] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [198] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_reference, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_reference, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_character, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_any_character, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_quantifers, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_quantifers, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_character, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_character, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture_group, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_capture_group, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_character, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_character, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_assertion, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_assertion, 1, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_set, 5, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set, 5, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_set_content_repeat1, 1, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_escaped, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_class, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_sequence, 1, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_any, 1, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_range, 3, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [297] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lua_patterns(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
